### ISSUE TITLE
Problem with sps in xevd_config function

### ISSUE THREAD

**Issue by dariusz-f** [mpeg5/xevd#17]
When function **xevd_config(XEVD id, int cfg, void * buf, int * size)** is used, xevd_app sample application and any other that is using xevd is crashing. 
This happens because sometimes inside xevd_config **sps** from context is null. 
https://github.com/mpeg5/xevd/blob/1385ab56687b097cec2e7c86b65be08e58ede5ef/src_main/xevdm.c#L3553

**Reproduction:**

1. uncomment line: https://github.com/mpeg5/xevd/blob/1385ab56687b097cec2e7c86b65be08e58ede5ef/app/xevd_app.c#L522
2. Run xevd_app with any video source.

**Backtrace:** 

```
(gdb) bt
#0  xevd_config (id=0x7ffff7f83010, cfg=402, buf=0x7fffffffd978, size=0x7fffffffd990)
    at /home/user/git/xevd/src_main/xevdm.c:3553
#1  0x0000555555559b80 in get_extra_config (id=0x7ffff7f83010)
    at /home/user/git/xevd/app/xevd_app.c:202
#2  0x000055555555a9be in main (argc=5, argv=0x7fffffffdc98)
    at /home/user/git/xevd/app/xevd_app.c:522
(gdb) 

(gdb) p ctx
$1 = (XEVD_CTX *) 0x7ffff7f83010

(gdb) p ctx->sps
$2 = (XEVD_SPS *) 0x0
```

**Comment by dariusz-f** [comment]
#18
